version: '3.8'

services:
  hq-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tournament_manager
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Denna tvingar Prisma att läsa och skriva databasen i vår säkra volym
      - DATABASE_URL=file:/app/data/prod.db
    volumes:
      # Mappar mappen 'data' på Linux-servern till '/app/data' i containern
      - ./data:/app/data
      # (Valfritt) Om du laddar upp egna loggor/pokaler som ska sparas över tid
      - ./public/prices:/app/public/prices
      - ./public/logos:/app/public/logos